Repository Frachtwerk/essencium-frontend, pull requests merged in 2025-04, with the labels that each got.

#753 fix: update dependencies
  packages/app/package.json
  packages/docs/package.json
  packages/docs/pnpm-lock.yaml
  packages/lib/package.json
  pnpm-lock.yaml
Labels: dependencies

#754 chore: release main
  .release-please-manifest.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/docs/CHANGELOG.md
  packages/docs/package.json
  packages/lib/CHANGELOG.md
  packages/lib/package.json
  packages/types/CHANGELOG.md
  packages/types/package.json
Labels: autorelease: pending

#759 758 child navitems not accessible in e2e tests and mobile view
  packages/lib/src/components/Header/components/UserMenu/UserMenu.tsx
  packages/lib/src/components/NavBar/components/NavLinks.tsx
Labels: bug

#756 chore: release main
  .release-please-manifest.json
  packages/app/CHANGELOG.md
  packages/app/package.json
  packages/lib/CHANGELOG.md
  packages/lib/package.json
Labels: autorelease: pending
